name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: emspregistry
  RESOURCE_GROUP: test
  CONTAINER_INSTANCE_NAME: emsp-container
  APPLICATION_NAME: emsp-interfaces

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -DskipTests=true clean package

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          az acr build --registry $AZURE_CONTAINER_REGISTRY \
                       --image $AZURE_CONTAINER_REGISTRY.azurecr.io/$APPLICATION_NAME:$GITHUB_SHA \
                       --file ./emsp-interfaces/src/Dockerfile \
                       --resource-group test \
                       --platform linux \
                       https://github.com/Phoenixcwx/emsp.git

      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group $RESOURCE_GROUP \
            --name $CONTAINER_INSTANCE_NAME \
            --image $AZURE_CONTAINER_REGISTRY.azurecr.io/$APPLICATION_NAME:$GITHUB_SHA \
            --ports 8080 \
            --registry-login-server $AZURE_CONTAINER_REGISTRY.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label $CONTAINER_INSTANCE_NAME \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --restart-policy OnFailure